// <auto-generated />
using System;
using MemoriaNote;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MemoriaNote.Migrations
{
    [DbContext(typeof(NoteDbContext))]
    [Migration("20180918001701_FtsIndexTable")]
    partial class FtsIndexTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.2-rtm-30932");

            modelBuilder.Entity("MemoriaNote.Content", b =>
                {
                    b.Property<string>("GuidAsString")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ContentType");

                    b.Property<DateTime>("CreateTime");

                    b.Property<int>("Index");

                    b.Property<bool>("IsErased");

                    b.Property<string>("Noteid")
                        .IsRequired();

                    b.Property<int>("Rowid");

                    b.Property<string>("TagsAsString");

                    b.Property<string>("Title");

                    b.Property<DateTime>("UpdateTime");

                    b.HasKey("GuidAsString");

                    b.HasIndex("Title", "Index");

                    b.ToTable("Contents");
                });

            modelBuilder.Entity("MemoriaNote.NoteKeyValue", b =>
                {
                    b.Property<string>("Key")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Value");

                    b.HasKey("Key");

                    b.ToTable("TitlePage");
                });

            modelBuilder.Entity("MemoriaNote.Page", b =>
                {
                    b.Property<int>("Rowid")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ContentType");

                    b.Property<DateTime>("CreateTime");

                    b.Property<string>("GuidAsString")
                        .IsRequired();

                    b.Property<int>("Index");

                    b.Property<bool>("IsErased");

                    b.Property<string>("Noteid")
                        .IsRequired();

                    b.Property<string>("TagsAsString");

                    b.Property<string>("Text");

                    b.Property<string>("Title");

                    b.Property<DateTime>("UpdateTime");

                    b.HasKey("Rowid");

                    b.HasAlternateKey("GuidAsString");

                    b.HasIndex("Title", "Index");

                    b.ToTable("Pages");
                });

            modelBuilder.Entity("MemoriaNote.PageHistory", b =>
                {
                    b.Property<int>("Rowid");

                    b.Property<int>("Generation");

                    b.Property<DateTime>("CreateTime");

                    b.Property<DateTime>("SaveTime");

                    b.Property<string>("TagsHash");

                    b.Property<string>("TagsPatch");

                    b.Property<string>("TextHash");

                    b.Property<string>("TextPatch");

                    b.Property<string>("TitleHash");

                    b.Property<string>("TitlePatch");

                    b.Property<DateTime>("UpdateTime");

                    b.HasKey("Rowid", "Generation");

                    b.ToTable("History");
                });
#pragma warning restore 612, 618
        }
    }
}
